// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesManagementSystem.Data.Context;

#nullable disable

namespace SalesManagementSystem.Data.Migrations
{
    [DbContext(typeof(SalesDbCOntext))]
    [Migration("20260225224715_Seeding")]
    partial class Seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("CreditLimit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<int>("SalesRepNum")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("SalesRepNum");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address1 = "Street 1",
                            City = "NY",
                            Country = "USA",
                            CreditLimit = 50000m,
                            FirstName = "Kevin",
                            LastName = "Lee",
                            Name = "AutoWorld",
                            Phone = "1111",
                            PostalCode = 10001,
                            SalesRepNum = 3,
                            State = "NY"
                        },
                        new
                        {
                            Id = 2,
                            Address1 = "Street 2",
                            City = "LA",
                            Country = "USA",
                            CreditLimit = 60000m,
                            FirstName = "Alex",
                            LastName = "Kim",
                            Name = "SpeedCars",
                            Phone = "2222",
                            PostalCode = 90001,
                            SalesRepNum = 3,
                            State = "CA"
                        },
                        new
                        {
                            Id = 3,
                            Address1 = "Street 3",
                            City = "Paris",
                            Country = "France",
                            CreditLimit = 70000m,
                            FirstName = "Jean",
                            LastName = "Dubois",
                            Name = "EuroMotors",
                            Phone = "3333",
                            PostalCode = 75000,
                            SalesRepNum = 4,
                            State = "Paris"
                        },
                        new
                        {
                            Id = 4,
                            Address1 = "Street 4",
                            City = "Berlin",
                            Country = "Germany",
                            CreditLimit = 55000m,
                            FirstName = "Max",
                            LastName = "Schulz",
                            Name = "BerlinCars",
                            Phone = "4444",
                            PostalCode = 10115,
                            SalesRepNum = 4,
                            State = "Berlin"
                        },
                        new
                        {
                            Id = 5,
                            Address1 = "Street 5",
                            City = "Tokyo",
                            Country = "Japan",
                            CreditLimit = 80000m,
                            FirstName = "Ken",
                            LastName = "Sato",
                            Name = "TokyoMotors",
                            Phone = "5555",
                            PostalCode = 150000,
                            SalesRepNum = 5,
                            State = "Tokyo"
                        },
                        new
                        {
                            Id = 6,
                            Address1 = "Street 6",
                            City = "NY",
                            Country = "USA",
                            CreditLimit = 45000m,
                            FirstName = "Chris",
                            LastName = "Miller",
                            Name = "TruckHub",
                            Phone = "6666",
                            PostalCode = 10002,
                            SalesRepNum = 5,
                            State = "NY"
                        },
                        new
                        {
                            Id = 7,
                            Address1 = "Street 7",
                            City = "Tokyo",
                            Country = "Japan",
                            CreditLimit = 62000m,
                            FirstName = "Li",
                            LastName = "Tan",
                            Name = "MotoX",
                            Phone = "7777",
                            PostalCode = 150001,
                            SalesRepNum = 6,
                            State = "Tokyo"
                        },
                        new
                        {
                            Id = 8,
                            Address1 = "Street 8",
                            City = "LA",
                            Country = "USA",
                            CreditLimit = 48000m,
                            FirstName = "Sam",
                            LastName = "White",
                            Name = "ClassicRide",
                            Phone = "8888",
                            PostalCode = 90002,
                            SalesRepNum = 6,
                            State = "CA"
                        },
                        new
                        {
                            Id = 9,
                            Address1 = "Street 9",
                            City = "NY",
                            Country = "USA",
                            CreditLimit = 53000m,
                            FirstName = "Carlos",
                            LastName = "Lopez",
                            Name = "FastLane",
                            Phone = "9999",
                            PostalCode = 10003,
                            SalesRepNum = 3,
                            State = "NY"
                        },
                        new
                        {
                            Id = 10,
                            Address1 = "Street 10",
                            City = "Paris",
                            Country = "France",
                            CreditLimit = 67000m,
                            FirstName = "Luis",
                            LastName = "Garcia",
                            Name = "PrimeAuto",
                            Phone = "1010",
                            PostalCode = 75001,
                            SalesRepNum = 4,
                            State = "Paris"
                        });
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Extension")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("JobTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("OfficeCode")
                        .HasColumnType("int");

                    b.Property<int?>("ReportsTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OfficeCode");

                    b.HasIndex("ReportsTo");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@company.com",
                            Extension = "101",
                            FirstName = "John",
                            JobTitle = "CEO",
                            LastName = "Smith",
                            OfficeCode = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "david@company.com",
                            Extension = "102",
                            FirstName = "David",
                            JobTitle = "Sales Manager",
                            LastName = "Brown",
                            OfficeCode = 1
                        },
                        new
                        {
                            Id = 3,
                            Email = "emma@company.com",
                            Extension = "201",
                            FirstName = "Emma",
                            JobTitle = "Sales Rep",
                            LastName = "Johnson",
                            OfficeCode = 2
                        },
                        new
                        {
                            Id = 4,
                            Email = "claire@company.com",
                            Extension = "301",
                            FirstName = "Claire",
                            JobTitle = "Sales Rep",
                            LastName = "Martin",
                            OfficeCode = 3
                        },
                        new
                        {
                            Id = 5,
                            Email = "lukas@company.com",
                            Extension = "401",
                            FirstName = "Lukas",
                            JobTitle = "Sales Rep",
                            LastName = "Schmidt",
                            OfficeCode = 4
                        },
                        new
                        {
                            Id = 6,
                            Email = "hiro@company.com",
                            Extension = "501",
                            FirstName = "Hiro",
                            JobTitle = "Sales Rep",
                            LastName = "Tanaka",
                            OfficeCode = 5
                        });
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Office", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<string>("Address1")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Address2")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Country")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("PostalCode")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Territory")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Code");

                    b.ToTable("Offices");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            Address1 = "5th Ave",
                            City = "New York",
                            Country = "USA",
                            Phone = "111111",
                            PostalCode = 10001,
                            State = "NY",
                            Territory = "NA"
                        },
                        new
                        {
                            Code = 2,
                            Address1 = "Sunset Blvd",
                            City = "Los Angeles",
                            Country = "USA",
                            Phone = "222222",
                            PostalCode = 90001,
                            State = "CA",
                            Territory = "NA"
                        },
                        new
                        {
                            Code = 3,
                            Address1 = "Champs Elysees",
                            City = "Paris",
                            Country = "France",
                            Phone = "333333",
                            PostalCode = 75000,
                            State = "Paris",
                            Territory = "EU"
                        },
                        new
                        {
                            Code = 4,
                            Address1 = "Alexanderplatz",
                            City = "Berlin",
                            Country = "Germany",
                            Phone = "444444",
                            PostalCode = 10115,
                            State = "Berlin",
                            Territory = "EU"
                        },
                        new
                        {
                            Code = 5,
                            Address1 = "Shibuya",
                            City = "Tokyo",
                            Country = "Japan",
                            Phone = "555555",
                            PostalCode = 150000,
                            State = "Tokyo",
                            Territory = "APAC"
                        });
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequireDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ShippedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerID");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Delivered",
                            CustomerID = 1,
                            OrderDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            Comments = "Delivered",
                            CustomerID = 2,
                            OrderDate = new DateTime(2025, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Comments = "Delivered",
                            CustomerID = 3,
                            OrderDate = new DateTime(2025, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 4,
                            Comments = "Delivered",
                            CustomerID = 4,
                            OrderDate = new DateTime(2025, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            Comments = "Delivered",
                            CustomerID = 5,
                            OrderDate = new DateTime(2025, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 6,
                            Comments = "Delivered",
                            CustomerID = 6,
                            OrderDate = new DateTime(2025, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 7,
                            Comments = "Delivered",
                            CustomerID = 7,
                            OrderDate = new DateTime(2025, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 8,
                            Comments = "Delivered",
                            CustomerID = 8,
                            OrderDate = new DateTime(2025, 1, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 9,
                            Comments = "Delivered",
                            CustomerID = 9,
                            OrderDate = new DateTime(2025, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 10,
                            Comments = "Delivered",
                            CustomerID = 10,
                            OrderDate = new DateTime(2025, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 1, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 11,
                            Comments = "Delivered",
                            CustomerID = 1,
                            OrderDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 12,
                            Comments = "Delivered",
                            CustomerID = 2,
                            OrderDate = new DateTime(2025, 2, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 2, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 13,
                            Comments = "Delivered",
                            CustomerID = 3,
                            OrderDate = new DateTime(2025, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 14,
                            Comments = "Delivered",
                            CustomerID = 4,
                            OrderDate = new DateTime(2025, 2, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 2, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 2, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        },
                        new
                        {
                            Id = 15,
                            Comments = "Delivered",
                            CustomerID = 5,
                            OrderDate = new DateTime(2025, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RequireDate = new DateTime(2025, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ShippedDate = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1
                        });
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Order_Product", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("ProductCode")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PriceEach")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Qty")
                        .HasColumnType("int");

                    b.HasKey("Id", "ProductCode", "OrderId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductCode");

                    b.ToTable("Order_Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductCode = 1,
                            OrderId = 1,
                            PriceEach = 25000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 2,
                            ProductCode = 6,
                            OrderId = 1,
                            PriceEach = 19000m,
                            Qty = 2
                        },
                        new
                        {
                            Id = 3,
                            ProductCode = 2,
                            OrderId = 2,
                            PriceEach = 23000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 4,
                            ProductCode = 7,
                            OrderId = 2,
                            PriceEach = 18000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 5,
                            ProductCode = 3,
                            OrderId = 3,
                            PriceEach = 27000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 6,
                            ProductCode = 11,
                            OrderId = 3,
                            PriceEach = 36000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 7,
                            ProductCode = 4,
                            OrderId = 4,
                            PriceEach = 26000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 8,
                            ProductCode = 8,
                            OrderId = 4,
                            PriceEach = 17500m,
                            Qty = 2
                        },
                        new
                        {
                            Id = 9,
                            ProductCode = 5,
                            OrderId = 5,
                            PriceEach = 24000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 10,
                            ProductCode = 9,
                            OrderId = 5,
                            PriceEach = 21000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 11,
                            ProductCode = 6,
                            OrderId = 6,
                            PriceEach = 19000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 12,
                            ProductCode = 12,
                            OrderId = 6,
                            PriceEach = 38000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 13,
                            ProductCode = 7,
                            OrderId = 7,
                            PriceEach = 18000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 14,
                            ProductCode = 13,
                            OrderId = 7,
                            PriceEach = 35000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 15,
                            ProductCode = 8,
                            OrderId = 8,
                            PriceEach = 17500m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 16,
                            ProductCode = 14,
                            OrderId = 8,
                            PriceEach = 37000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 17,
                            ProductCode = 9,
                            OrderId = 9,
                            PriceEach = 21000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 18,
                            ProductCode = 15,
                            OrderId = 9,
                            PriceEach = 34000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 19,
                            ProductCode = 10,
                            OrderId = 10,
                            PriceEach = 20000m,
                            Qty = 1
                        },
                        new
                        {
                            Id = 20,
                            ProductCode = 1,
                            OrderId = 10,
                            PriceEach = 25000m,
                            Qty = 1
                        });
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Payment", b =>
                {
                    b.Property<string>("CheckNum")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CustomerID")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CheckNum");

                    b.HasIndex("CustomerID");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Product", b =>
                {
                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MSRP")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PdtDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("ProductLineId")
                        .HasColumnType("int");

                    b.Property<int?>("QtyInStock")
                        .HasColumnType("int");

                    b.Property<int?>("Scale")
                        .HasColumnType("int");

                    b.Property<string>("Vendor")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Code");

                    b.HasIndex("ProductLineId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Code = 1,
                            BuyPrice = 20000m,
                            MSRP = "25000",
                            Name = "1969 Ford Mustang",
                            PdtDescription = "Classic Mustang",
                            ProductLineId = 1,
                            QtyInStock = 50,
                            Scale = 1,
                            Vendor = "AutoArt"
                        },
                        new
                        {
                            Code = 2,
                            BuyPrice = 18000m,
                            MSRP = "23000",
                            Name = "1957 Chevy Bel Air",
                            PdtDescription = "Vintage Chevy",
                            ProductLineId = 1,
                            QtyInStock = 40,
                            Scale = 1,
                            Vendor = "AutoArt"
                        },
                        new
                        {
                            Code = 3,
                            BuyPrice = 22000m,
                            MSRP = "27000",
                            Name = "1970 Dodge Charger",
                            PdtDescription = "Muscle car",
                            ProductLineId = 1,
                            QtyInStock = 30,
                            Scale = 1,
                            Vendor = "Highway66"
                        },
                        new
                        {
                            Code = 4,
                            BuyPrice = 21000m,
                            MSRP = "26000",
                            Name = "1965 Corvette",
                            PdtDescription = "Classic Corvette",
                            ProductLineId = 1,
                            QtyInStock = 35,
                            Scale = 1,
                            Vendor = "Highway66"
                        },
                        new
                        {
                            Code = 5,
                            BuyPrice = 19500m,
                            MSRP = "24000",
                            Name = "1967 Camaro",
                            PdtDescription = "Camaro SS",
                            ProductLineId = 1,
                            QtyInStock = 25,
                            Scale = 1,
                            Vendor = "AutoArt"
                        },
                        new
                        {
                            Code = 6,
                            BuyPrice = 15000m,
                            MSRP = "19000",
                            Name = "Harley Davidson",
                            PdtDescription = "Cruiser bike",
                            ProductLineId = 2,
                            QtyInStock = 60,
                            Scale = 1,
                            Vendor = "MotoWorld"
                        },
                        new
                        {
                            Code = 7,
                            BuyPrice = 14000m,
                            MSRP = "18000",
                            Name = "Yamaha R1",
                            PdtDescription = "Sport bike",
                            ProductLineId = 2,
                            QtyInStock = 45,
                            Scale = 1,
                            Vendor = "MotoWorld"
                        },
                        new
                        {
                            Code = 8,
                            BuyPrice = 13500m,
                            MSRP = "17500",
                            Name = "Kawasaki Ninja",
                            PdtDescription = "Racing bike",
                            ProductLineId = 2,
                            QtyInStock = 55,
                            Scale = 1,
                            Vendor = "SpeedX"
                        },
                        new
                        {
                            Code = 9,
                            BuyPrice = 17000m,
                            MSRP = "21000",
                            Name = "Ducati Monster",
                            PdtDescription = "Italian bike",
                            ProductLineId = 2,
                            QtyInStock = 20,
                            Scale = 1,
                            Vendor = "SpeedX"
                        },
                        new
                        {
                            Code = 10,
                            BuyPrice = 16000m,
                            MSRP = "20000",
                            Name = "BMW GS",
                            PdtDescription = "Adventure bike",
                            ProductLineId = 2,
                            QtyInStock = 30,
                            Scale = 1,
                            Vendor = "MotoWorld"
                        },
                        new
                        {
                            Code = 11,
                            BuyPrice = 30000m,
                            MSRP = "36000",
                            Name = "Ford F150",
                            PdtDescription = "Pickup truck",
                            ProductLineId = 3,
                            QtyInStock = 70,
                            Scale = 1,
                            Vendor = "TruckPro"
                        },
                        new
                        {
                            Code = 12,
                            BuyPrice = 32000m,
                            MSRP = "38000",
                            Name = "RAM 1500",
                            PdtDescription = "Heavy duty truck",
                            ProductLineId = 3,
                            QtyInStock = 65,
                            Scale = 1,
                            Vendor = "TruckPro"
                        },
                        new
                        {
                            Code = 13,
                            BuyPrice = 29000m,
                            MSRP = "35000",
                            Name = "Toyota Tundra",
                            PdtDescription = "Reliable truck",
                            ProductLineId = 3,
                            QtyInStock = 50,
                            Scale = 1,
                            Vendor = "TruckPro"
                        },
                        new
                        {
                            Code = 14,
                            BuyPrice = 31000m,
                            MSRP = "37000",
                            Name = "Chevy Silverado",
                            PdtDescription = "Work truck",
                            ProductLineId = 3,
                            QtyInStock = 45,
                            Scale = 1,
                            Vendor = "TruckPro"
                        },
                        new
                        {
                            Code = 15,
                            BuyPrice = 28000m,
                            MSRP = "34000",
                            Name = "Nissan Titan",
                            PdtDescription = "Strong truck",
                            ProductLineId = 3,
                            QtyInStock = 35,
                            Scale = 1,
                            Vendor = "TruckPro"
                        });
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.ProductLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescInHTML")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DescInText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Image")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProductLines");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DescInHTML = "Classic Cars Collection",
                            DescInText = "Classic Cars",
                            Image = "classic.jpg"
                        },
                        new
                        {
                            Id = 2,
                            DescInHTML = "Motorcycles Collection",
                            DescInText = "Motorcycles",
                            Image = "motorcycles.jpg"
                        },
                        new
                        {
                            Id = 3,
                            DescInHTML = "Trucks Collection",
                            DescInText = "Trucks",
                            Image = "trucks.jpg"
                        });
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Customer", b =>
                {
                    b.HasOne("SalesManagementSystem.Data.Models.Employee", "Employee")
                        .WithMany("Customers")
                        .HasForeignKey("SalesRepNum")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Employee", b =>
                {
                    b.HasOne("SalesManagementSystem.Data.Models.Office", "Office")
                        .WithMany("Employees")
                        .HasForeignKey("OfficeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagementSystem.Data.Models.Employee", "Supervisor")
                        .WithMany("Employees")
                        .HasForeignKey("ReportsTo")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Office");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Order", b =>
                {
                    b.HasOne("SalesManagementSystem.Data.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Order_Product", b =>
                {
                    b.HasOne("SalesManagementSystem.Data.Models.Order", "Order")
                        .WithMany("Order_Products")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SalesManagementSystem.Data.Models.Product", "Product")
                        .WithMany("Order_Products")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Payment", b =>
                {
                    b.HasOne("SalesManagementSystem.Data.Models.Customer", "Customer")
                        .WithMany("Purchases")
                        .HasForeignKey("CustomerID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Product", b =>
                {
                    b.HasOne("SalesManagementSystem.Data.Models.ProductLine", "ProductLine")
                        .WithMany("Products")
                        .HasForeignKey("ProductLineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ProductLine");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Customer", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Purchases");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Employee", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Office", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Order", b =>
                {
                    b.Navigation("Order_Products");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.Product", b =>
                {
                    b.Navigation("Order_Products");
                });

            modelBuilder.Entity("SalesManagementSystem.Data.Models.ProductLine", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
